#:schema node_modules/wrangler/config-schema.json
name = "querido-camp"
main = ".open-next/worker.js"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

# Remova a seção [site] e use [assets]
[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[vars]
# Suas variáveis aqui

[[hyperdrive]]
binding = "DB_PRINCIPAL"
id = "1824943cc777470591f56e5a1857256b"
local_connection_string = "mysql://root:YMQZnBJRGFhRYSfjSZjFMGTegALnUfoS@nozomi.proxy.rlwy.net:36657/railway"

[[hyperdrive]]
binding = "DB_JOGADORES"
id = "aa334a49183040a6bdc1d4eaa38341e5"
local_connection_string = "mysql://root:fDCcXUwqZhgwPRXMUKDTtrKiRARETYOE@hopper.proxy.rlwy.net:53994/railway"