#:schema node_modules/wrangler/config-schema.json
name = "querido-camp"
main = ".open-next/worker.js"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

# Remova a seção [site] e use [assets]
[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[vars]
# Suas variáveis aqui

[[hyperdrive]]
binding = "hostinger"
id = "79de15ef75944ae2934beb5a5150b3f0"
local_connection_string = "mysql://botuser:aF!0_%40MM360J@187.77.45.123:3306/bancoks"
