name: Deploy Frontend
on:
  push:
    branches: [ "main" ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: "ubuntu"
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Entra na pasta, puxa o código novo e volta
            cd /home/ubuntu/front-end && git pull origin main && cd ..
            
            # --- COMANDOS PARA NÃO TRAVAR E ATUALIZAR O SITE ---
            
            # 1. Limpa a cache de builds antigos para liberar RAM
            docker builder prune -a -f
            
            # 2. Para os containers para liberar memória para o novo build
            docker-compose down
            
            # 3. Reconstrói o container com o código novo (forçando atualização)
            docker-compose up --build --force-recreate -d
            
            # 4. Limpeza de imagens antigas
            docker image prune -f