name: Deploy Frontend
on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: "ubuntu"
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          command_timeout: 30m
          script: |
            cd /home/ubuntu/front-end
            
            echo "--- Limpando Git e Forçando Pull ---"
            git clean -fd
            git fetch origin main
            git reset --hard origin/main
            
            echo "--- Liberando Espaço no SSD ---"
            docker builder prune -a -f
            docker image prune -f
            
            echo "--- Iniciando Build (Hardware 1GB RAM) ---"
            cd ..
            docker compose up -d --build --no-cache
            
            echo "--- Status Final ---"
            docker ps --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}"